version: '3'
services:
  sociobio:
    container_name: sociobio
    restart: always
    build: .
    links:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/sociobio
      - SECRET=LBHbQJpuZT
    volumes:
      - ./uploads:/app/uploads
    labels:
      - "traefik.backend=sociobio"
      - "traefik.frontend.rule=Host:sociobio.terrakrya.tk"
  mongo:
    container_name: sociobio-mongo
    image: 'mongo:4'
    volumes:
      - ./data:/data/db
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
