version: "3"

services:
  sociobio_app:
    container_name: sociobio
    restart: always
    build: .
    links:
      - mongo_sociobio
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo_sociobio:27017/sociobio
      - SECRET=LBHbQJpuZT
      - PORT=80
    volumes:
      - ./uploads/sociobio:/app/uploads
    labels:
      - 'traefik.docker.network=sociobio'
      - 'traefik.backend=sociobio'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:sociobio.terrakrya.tk'
      - 'traefik.enable=true'
    depends_on:
      - traefik
      - mongo_sociobio
  mongo_sociobio:
    container_name: mongo_sociobio
    image: 'mongo:4'
    restart: always
    volumes:
      - ./data/sociobio:/data/db
    depends_on:
      - traefik

  traefik:
    image: traefik
    restart: always
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.docker.network=sociobio"
