version: "3"

services:
  alimentodafonte_app:
    container_name: alimentodafonte
    restart: always
    build: .
    links:
      - mongo_alimentodafonte
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo_alimentodafonte:27017/alimentodafonte
      - SECRET=LBHbQJpuZT
      - PORT=80
    volumes:
      - ./uploads/alimentodafonte:/app/uploads
    labels:
      - 'traefik.docker.network=alimentodafonte'
      - 'traefik.backend=alimentodafonte'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:alimentodafonte.terrakrya.tk'
      - 'traefik.enable=true'
    depends_on:
      - mongo_alimentodafonte
  mongo_alimentodafonte:
    container_name: mongo_alimentodafonte
    image: 'mongo:4'
    restart: always
    volumes:
      - ./data/alimentodafonte:/data/db
