version: '3'
services:
  sementes:
    container_name: sementes
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/sementes
      - SECRET=LBHbQJpuZT
    volumes:
      - ./uploads:/app/uploads
  mongo:
    container_name: sementes-mongo
    image: 'mongo:4'
    volumes:
      - ./data:/data/db
