version: "3"

services:
  sementes:
    container_name: sementes
    restart: always
    build: .
    links:
      - mongo_sementes
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/sementes
      - SECRET=LBHbQJpuZT
    volumes:
      - ./uploads:/app/uploads
    networks:
      sementes_sementes:
    labels:
      - 'traefik.docker.network=drupal'
      - 'traefik.backend=sementes'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:sementes.nyx.tc'
      - 'traefik.enable=true'
      
  mongo_sementes:
    container_name: mongo_sementes
    image: 'mongo:4'
    volumes:
      - ./data:/data/db

networks:
  sementes_sementes:
    external: true
